nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS']
        allow_headers: ['Content-Type', 'X-AUTH-TOKEN']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null